import './dataTypes/Number';
import './dataTypes/Length';
import './dataTypes/Percentage';
import './dataTypes/URL';
import './dataTypes/Image';
import './properties/Background';
import './properties/BackgroundPosition';
import './properties/BackgroundRepeat';
import './properties/BackgroundSize';
